name: "Traccar Server"
version: "1.0.2"
slug: "traccar"
description: "Traccar GPS tracking server for Home Assistant"
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: auto
init: false
host_network: true
options:
  database_driver: "com.mysql.cj.jdbc.Driver"
  database_url: "jdbc:mysql://core-mariadb:3306/traccar?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&allowMultiQueries=true&autoReconnect=true"
  database_user: "traccar"
  database_password: "cambiami_con_password_db"
schema:
  database_driver: str
  database_url: str
  database_user: str
  database_password: str
